//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.PS.Common.Vault.Explorer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
[
  {
    ""Alias"": ""WD.Services US Int"",
    ""VaultNames"": [""wdvaultus1westint"", ""wdvaultus1eastint""]
  },
  {
    ""Alias"": ""WD.Services US PPE"",
    ""VaultNames"": [""wdvaultus1westppe"", ""wdvaultus1eastppe""]
  },
  {
    ""Alias"": ""WD.Services US Prod"",
    ""VaultNames"": [""wdvaultus1westprod"", ""wdvaultus1eastprod""]
  },
  {
    ""Alias"": ""WD.Services AU Prod"",
    ""VaultNames"": [""wdvaultau1eastprod"", ""wdvaultau1southeastprod""]
  },
  {
    ""Alias"": ""Defender Key Vault Ops"",
    ""VaultNames"": [""defenderkeyvault""]
  },
  {
    ""Alias"": ""Defender Key Vault Dev"",
    ""VaultNames"": [""defenderkeyvaultdev""]
  },
  {
    ""Alias"": ""Defender Key Vault Research"",
    ""VaultNames"": [""defenderkeyvaultresearch""]
  },
  {
    ""Alias"": ""Defender Key Vault Build"",
    ""VaultNames"": [""defenderkeyvaultbuild""]
  },
]
                ")]
        public string VaultAliases {
            get {
                return ((string)(this["VaultAliases"]));
            }
            set {
                this["VaultAliases"] = value;
            }
        }
    }
}
