//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Vault.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Vault.Core.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception has been detected in the current application domain {0}. See below for details. 的本地化字符串。
        /// </summary>
        internal static string AppDomainUnhandledException {
            get {
                return ResourceManager.GetString("AppDomainUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception has been detected in the current application domain {0}. There was no exception object available for detailed information. 的本地化字符串。
        /// </summary>
        internal static string AppDomainUnhandledExceptionNoDetails {
            get {
                return ResourceManager.GetString("AppDomainUnhandledExceptionNoDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be initialized with its default value. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeDefault {
            get {
                return ResourceManager.GetString("ArgumentCannotBeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be greater than its ceiling value of {1}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeGreaterThanBaseline {
            get {
                return ResourceManager.GetString("ArgumentCannotBeGreaterThanBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be initialized with a negative value. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeNegative {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be out of range ({1} - {2}). 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentCannotBeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be initialized with a zero or negative value. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCannotBeZeroOrNegative {
            get {
                return ResourceManager.GetString("ArgumentCannotBeZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} cannot be a null or empty collection. 的本地化字符串。
        /// </summary>
        internal static string ArgumentCollectionCannotBeEmpty {
            get {
                return ResourceManager.GetString("ArgumentCollectionCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified argument {0} is not in collection {1}. 的本地化字符串。
        /// </summary>
        internal static string ArgumentNotInCollection {
            get {
                return ResourceManager.GetString("ArgumentNotInCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The values of the specified argument {0} do not satisfy the required condition. 的本地化字符串。
        /// </summary>
        internal static string ArgumentsConditionNotSatisfied {
            get {
                return ResourceManager.GetString("ArgumentsConditionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data in the specified blob of type {0} cannot be null. 的本地化字符串。
        /// </summary>
        internal static string BlobDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("BlobDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A failure has occurred while downloading blob {0} from the container {1}. The download operation cannot be retried as data consistency cannot be guaranteed. This could be due to the blob’s data stream being non-rewindable (non-seekable) or other conditions that cannot be compensated by a retry. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string BlobDownloadCannotBeRetried {
            get {
                return ResourceManager.GetString("BlobDownloadCannotBeRetried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to upload the blob(s). The asynchronous operation has been terminated with an unexpected error. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string BlobPutAsyncOperationFailure {
            get {
                return ResourceManager.GetString("BlobPutAsyncOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A failure has occurred while uploading blob {0} in the container {1}. The upload operation cannot be retried as data consistency cannot be guaranteed. This could be due to the blob’s data stream being non-rewindable (non-seekable) or other conditions that cannot be compensated by a retry. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string BlobUploadCannotBeRetried {
            get {
                return ResourceManager.GetString("BlobUploadCannotBeRetried", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An instance of {0} object cannot be created from the specified instance of XML reader. The reader is expected to be positioned on element {0} from namespace {1}. Encountered element {2} in namespace {3}. 的本地化字符串。
        /// </summary>
        internal static string CannotCreateInstanceFromXmlReader {
            get {
                return ResourceManager.GetString("CannotCreateInstanceFromXmlReader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Transferring large messages requires an overflow message store. Please make sure that the overflow store was specified. 的本地化字符串。
        /// </summary>
        internal static string CannotHandleLargeMessageWithoutOverflowStore {
            get {
                return ResourceManager.GetString("CannotHandleLargeMessageWithoutOverflowStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse the specified Service Bus endpoint connection string {0}. The value appears to be in the wrong format. Please refer to the documentation for details. 的本地化字符串。
        /// </summary>
        internal static string CannotParseServiceBusConnectionString {
            get {
                return ResourceManager.GetString("CannotParseServiceBusConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to parse the specified storage account connection string {0}. The value appears to be in the wrong format. Please refer to the documentation for details. 的本地化字符串。
        /// </summary>
        internal static string CannotParseStorageConnectionString {
            get {
                return ResourceManager.GetString("CannotParseStorageConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified client ID value cannot be used for computation. The provided number results in an out-of-bound value. 的本地化字符串。
        /// </summary>
        internal static string ClientIdValueCannotBeUsedForComputingPartitionId {
            get {
                return ResourceManager.GetString("ClientIdValueCannotBeUsedForComputingPartitionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 的本地化字符串。
        /// </summary>
        internal static string CloudWebAppBaseUnhandledException {
            get {
                return ResourceManager.GetString("CloudWebAppBaseUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application&apos;s configuration file (such as ServiceConfiguration.cscfg, app.config or web.config) doesn&apos;t contain a section {0}. This section is compulsory for the application in order to function properly. Please add this section into the configuration file. 的本地化字符串。
        /// </summary>
        internal static string ConfigSectionNotFound {
            get {
                return ResourceManager.GetString("ConfigSectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type of the configuration section {0} cannot be reliably determined. Instead of specifying the type {1}, use a more specific type or make sure that the configuration data possesses the type information. For more details, please refer to the relevant sectionsin the API documentation. 的本地化字符串。
        /// </summary>
        internal static string ConfigSectionTypeCannotBeDetermined {
            get {
                return ResourceManager.GetString("ConfigSectionTypeCannotBeDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A connection string for the {0} database has not been found in the application configuration. Please verify the current configuration and make sure that the ConnectionStrings section contains a valid definition of the connection string for {0}. 的本地化字符串。
        /// </summary>
        internal static string ConnectionStringNotDefined {
            get {
                return ResourceManager.GetString("ConnectionStringNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container names must start with a letter or number, and can contain only letters, numbers, and the dash (-) character. 的本地化字符串。
        /// </summary>
        internal static string ContainerNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("ContainerNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Every dash (-) character must be immediately preceded and followed by a letter or number. 的本地化字符串。
        /// </summary>
        internal static string ContainerNameInvalidDashSequence {
            get {
                return ResourceManager.GetString("ContainerNameInvalidDashSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container names must be from 3 through 63 characters long. Please refer to the &quot;Naming Containers, Blobs, and Metadata&quot; section in the MSDN library for more information. 的本地化字符串。
        /// </summary>
        internal static string ContainerNameTooLong {
            get {
                return ResourceManager.GetString("ContainerNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Container names must be at least 3 characters long. Please refer to the &quot;Naming Containers, Blobs, and Metadata&quot; section in the MSDN library for more information. 的本地化字符串。
        /// </summary>
        internal static string ContainerNameTooShort {
            get {
                return ResourceManager.GetString("ContainerNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The configured XML namespace prefix has already been assigned to a different namespace. Please verify the XPath Query Library and make sure that all prefixes are unique. 的本地化字符串。
        /// </summary>
        internal static string DuplicatePrefixFoundInNamespaceCollection {
            get {
                return ResourceManager.GetString("DuplicatePrefixFoundInNamespaceCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified collection of endpoint definitions doesn&apos;t not contain any items. The collection must not be empty. 的本地化字符串。
        /// </summary>
        internal static string EndpointCollectionIsEmpty {
            get {
                return ResourceManager.GetString("EndpointCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to write an event into the ETW stack. Error code: {0}. 的本地化字符串。
        /// </summary>
        internal static string EtwWriteEventFailure {
            get {
                return ResourceManager.GetString("EtwWriteEventFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An instance of type {0} has not been found in the collection of registered extensions. Please make sure that an extension of this type is correctly and timely registered to enable its consumers to locate the instance at runtime. 的本地化字符串。
        /// </summary>
        internal static string ExtensionObjectNotFound {
            get {
                return ResourceManager.GetString("ExtensionObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current ASP.NET application does not appear to have been correctly configured to work with the CloudFx extensibility model. The required state variable is missing from the application’s state. Please make sure that the ASP.NET application’s entry point (which is usually the Global.asax.cs file) inherits from the {0} type. By inheriting from this type, the ASP.NET application will be automatically enabled for extensibility with no further user actions required. 的本地化字符串。
        /// </summary>
        internal static string ExtensionObjectNotFoundInAspNetState {
            get {
                return ResourceManager.GetString("ExtensionObjectNotFoundInAspNetState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The incoming message cannot be deserialized successfully into an instance of type {0}. Please ensure that the sender correctly serialized the outbound messages and that both the sender and receiver share the same serialization component. 的本地化字符串。
        /// </summary>
        internal static string IncomingMessageCannotBeDeserialized {
            get {
                return ResourceManager.GetString("IncomingMessageCannotBeDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The incoming message cannot be processed. The required property {0} is missing from the message context. Please ensure that the sender correctly stamped the outbound messages with the above property. 的本地化字符串。
        /// </summary>
        internal static string IncomingMessageMissingRequiredProperty {
            get {
                return ResourceManager.GetString("IncomingMessageMissingRequiredProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified number of Service Bus endpoints ({0}) is insufficient for scale-out purposes. The recommended number of endpoints should be a percentage of the total number of publishers and subscribers, or at least greater than 2. 的本地化字符串。
        /// </summary>
        internal static string InsufficientNumberOfEndpoints {
            get {
                return ResourceManager.GetString("InsufficientNumberOfEndpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of argument {0} must be {1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidArgumentValue {
            get {
                return ResourceManager.GetString("InvalidArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified value {0} is not a valid Windows Azure table name. 的本地化字符串。
        /// </summary>
        internal static string InvalidCloudTableName {
            get {
                return ResourceManager.GetString("InvalidCloudTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must be valid Ctph. 的本地化字符串。
        /// </summary>
        internal static string InvalidCtph {
            get {
                return ResourceManager.GetString("InvalidCtph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value of the argument {0} provided for the enumeration {1} is invalid. 的本地化字符串。
        /// </summary>
        internal static string InvalidEnumValue {
            get {
                return ResourceManager.GetString("InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must be a valid MD5. 的本地化字符串。
        /// </summary>
        internal static string InvalidMd5 {
            get {
                return ResourceManager.GetString("InvalidMd5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified Service Bus endpoint definition {0} is of a wrong type {1}. The expected type is {2}. 的本地化字符串。
        /// </summary>
        internal static string InvalidServiceBusEndpointType {
            get {
                return ResourceManager.GetString("InvalidServiceBusEndpointType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must be valid Sha{1}. 的本地化字符串。
        /// </summary>
        internal static string InvalidSha {
            get {
                return ResourceManager.GetString("InvalidSha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must be valid {1} prefix with at least 6 hex digits and upto 39 or 63 chars long accordingly. 的本地化字符串。
        /// </summary>
        internal static string InvalidShaPrefix {
            get {
                return ResourceManager.GetString("InvalidShaPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The requested action against the collection of Windows Azure role settings cannot be performed due to API restrictions. The settings cannot be modified, removed or retrieved by their index. 的本地化字符串。
        /// </summary>
        internal static string InvalidUseOfRoleConfigurationSettingCollection {
            get {
                return ResourceManager.GetString("InvalidUseOfRoleConfigurationSettingCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to publish the message(s). The asynchronous operation has been terminated with an unexpected error. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string PublishAsyncOperationFailure {
            get {
                return ResourceManager.GetString("PublishAsyncOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to publish the message. The definition for the endpoint {0} cannot be found. Please ensure that the specified endpoint definition has been registered in the endpoint collection. 的本地化字符串。
        /// </summary>
        internal static string PublishFailureEndpointNotFound {
            get {
                return ResourceManager.GetString("PublishFailureEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to publish the message. There were no endpoints found that match the specified name or pattern. 的本地化字符串。
        /// </summary>
        internal static string PublishFailureNoMatchingEndpointsFound {
            get {
                return ResourceManager.GetString("PublishFailureNoMatchingEndpointsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified queue name template {0} must include a placeholder “{1}” which will be used for customizing the queue names to be able to create multiple queues for scaling purposes. 的本地化字符串。
        /// </summary>
        internal static string QueueNameTemplateNameMustIncludePlaceholder {
            get {
                return ResourceManager.GetString("QueueNameTemplateNameMustIncludePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to enqueue the message(s). The asynchronous operation has been terminated with an unexpected error. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string QueuePutAsyncOperationFailure {
            get {
                return ResourceManager.GetString("QueuePutAsyncOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The action has exceeded its defined retry limit. 的本地化字符串。
        /// </summary>
        internal static string RetryLimitExceeded {
            get {
                return ResourceManager.GetString("RetryLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified endpoint address {0} has not been found in the Service Registry. 的本地化字符串。
        /// </summary>
        internal static string ServiceRegistryEndpointNotFound {
            get {
                return ResourceManager.GetString("ServiceRegistryEndpointNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The definition for the Service Bus endpoint {0} is expected to have been of type {1}. The actual type of the endpoint is {2}. Please ensure that the endpoint type is set to the correct type. 的本地化字符串。
        /// </summary>
        internal static string SpecifiedServiceBusEndpointIsOfWrongType {
            get {
                return ResourceManager.GetString("SpecifiedServiceBusEndpointIsOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The definition for the Service Bus endpoint {0} has an empty topic path. The path must be set to the correct value. 的本地化字符串。
        /// </summary>
        internal static string SpecifiedServiceBusEndpointTopicPathEmpty {
            get {
                return ResourceManager.GetString("SpecifiedServiceBusEndpointTopicPathEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified collection of storage accounts doesn&apos;t not contain any items. The collection must not be empty. 的本地化字符串。
        /// </summary>
        internal static string StorageAccountCollectionIsEmpty {
            get {
                return ResourceManager.GetString("StorageAccountCollectionIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must not be empty. 的本地化字符串。
        /// </summary>
        internal static string StringCannotBeEmpty {
            get {
                return ResourceManager.GetString("StringCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument {0} must be a valid table name. 的本地化字符串。
        /// </summary>
        internal static string StringMustBeAValidTableName {
            get {
                return ResourceManager.GetString("StringMustBeAValidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified string argument &apos;{0}&apos; must match the given Regex pattern &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string StringMustMatchRegex {
            get {
                return ResourceManager.GetString("StringMustMatchRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to subscribe to messages from the publish/subscribe channel of type {0}. The operation has been terminated with an unexpected error. Please refer to the inner exception for details. 的本地化字符串。
        /// </summary>
        internal static string SubscribeOperationFailure {
            get {
                return ResourceManager.GetString("SubscribeOperationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified subscription name {0} cannot be found or cannot be created on topic {1}. Please check if the name is valid. The maximum supported length of subscription names is 290 characters. The name should only contain alphanumeric characters. 的本地化字符串。
        /// </summary>
        internal static string SubscriptionCannotBeCreatedOrFound {
            get {
                return ResourceManager.GetString("SubscriptionCannotBeCreatedOrFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified subscription name {0} must include a placeholder “{1}” which will be used for customizing the subscription name for each individual non-competing subscriber. 的本地化字符串。
        /// </summary>
        internal static string SubscriptionNameMustIncludePlaceholder {
            get {
                return ResourceManager.GetString("SubscriptionNameMustIncludePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All entities must share the same PartitionKey property. 的本地化字符串。
        /// </summary>
        internal static string TableEntityCollectionPartitionKeyMismatch {
            get {
                return ResourceManager.GetString("TableEntityCollectionPartitionKeyMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified table entity does not contain a partition key, or its value is null. Please make sure that the table entity inherits from one of the following types: {0} or has a public property called {1}. Please also make sure that the partition key value conforms to the requirements set out by the Table Storage service. 的本地化字符串。
        /// </summary>
        internal static string TableEntityInvalidPartitionKey {
            get {
                return ResourceManager.GetString("TableEntityInvalidPartitionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified table entity does not contain a row key, or its value is null. Please make sure that the table entity inherits from one of the following types: {0} or has a public property called {1}. Please also make sure that the row key value conforms to the requirements set out by the Table Storage service. 的本地化字符串。
        /// </summary>
        internal static string TableEntityInvalidRowKey {
            get {
                return ResourceManager.GetString("TableEntityInvalidRowKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified table entity type {0} cannot be used with this component. The supported entity types are: {1} or any type containing public properties called {2} and {3}. Please make sure you either use any of the supported types or both the Partition and Row key properties are defined as public properties. 的本地化字符串。
        /// </summary>
        internal static string TableEntityUnsupportedType {
            get {
                return ResourceManager.GetString("TableEntityUnsupportedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table names must be from 3 to 63 characters long, they may contain only alphanumeric characters and cannot begin with a numeric character. 的本地化字符串。
        /// </summary>
        internal static string TableNameContainsInvalidCharacters {
            get {
                return ResourceManager.GetString("TableNameContainsInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to complete the requested table storage operation. See inner exception(s) for details. 的本地化字符串。
        /// </summary>
        internal static string TableStorageOperationFailed {
            get {
                return ResourceManager.GetString("TableStorageOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to complete the requested table storage operation. The Table Storage Service returned the following response code(s): {0}. See inner exception(s) for details. 的本地化字符串。
        /// </summary>
        internal static string TableStorageOperationFailedWithResponseCode {
            get {
                return ResourceManager.GetString("TableStorageOperationFailedWithResponseCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified topic name {0} cannot be found or cannot be created. Please check if the name is valid. The maximum supported length of topic path is 290 characters. The name should only contain alphanumeric characters. 的本地化字符串。
        /// </summary>
        internal static string TopicCannotBeCreatedOrFound {
            get {
                return ResourceManager.GetString("TopicCannotBeCreatedOrFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified trace provider GUID {0} cannot be found. Please make sure that a trace event provider with a matching GUID value has been registered with Trace Manager. 的本地化字符串。
        /// </summary>
        internal static string TraceProviderGuidCannotBeFound {
            get {
                return ResourceManager.GetString("TraceProviderGuidCannotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified type {0} is missing the required attribute {1}. Please make sure that the type has been decorated with the above attribute. 的本地化字符串。
        /// </summary>
        internal static string TypeMissingRequiredAttribute {
            get {
                return ResourceManager.GetString("TypeMissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The specified type {0} is not compatible with {1}. 的本地化字符串。
        /// </summary>
        internal static string TypeNotCompatible {
            get {
                return ResourceManager.GetString("TypeNotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A definition for the {0} XPath query has not been found in the XPath Query Library. Please make sure that the corresponding configuration file contains a valid definition for this query. 的本地化字符串。
        /// </summary>
        internal static string XPathQueryNotDefined {
            get {
                return ResourceManager.GetString("XPathQueryNotDefined", resourceCulture);
            }
        }
    }
}
